---
- name: Add DSC modules
  hosts: all
  gather_facts: no
  tasks:
#  necessary because of https://github.com/ansible/ansible/issues/50332
  - name: Enable Nuget
    win_shell: Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
  
  - name: Install ComputerManagementDsc
    win_psmodule:
      name: ComputerManagementDsc
      url: 'http://192.168.0.180:8081/repository/powershell/'
      repository: 'LocalRepository'
      state: present
      
      