---
- name: Add DSC modules
  hosts: all
  gather_facts: no
  tasks:

  - name: Install "{{ item }}" module
    win_psmodule:
      name: "{{ item }}"
      url: 'http://192.168.0.180:8081/repository/powershell/'
      repository: 'LocalRepository'
      state: present
    loop:
      - ComputerManagementDsc
      - NetworkingDsc
      - xRemoteDesktopAdmin
      - CertificateDsc
      - xActiveDirectory
      - xPendingReboot
      - WSManDsc
      