---
- name: Install PSGallery modules
  win_psmodule:
    name: "{{ item }}"
    repository: "{{ nuget_repository_repo | default(omit) }}"
    url: "{{ nuget_repository_url | default(omit) }}"
    state: present
  loop:
    - xActiveDirectory
    - xDNSServer

- name: Install pre-requisites (+ AD PowerShell cmdlets)
  win_feature:
    name: 
     - AD-Domain-Services
     - RSAT-AD-PowerShell
     # TODO fact check...
     # do we need this on a core install?  
     # probably.. there are some CLI tools here-in
     - RSAT-ADDS-Tools

# this will influence what the built in domain admin account will be called
- name: change the local admin account name
  win_security_policy:
    section: System Access
    key: NewAdministratorName
    value: "{{ addc_domainadmin }}"

# make sure it is complex enough, otherwise Computer Says No when installing AD.
# Err#43 - https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/troubleshooting-domain-controller-deployment
- name: Set password of local admin account
  win_user:
    name: "{{ addc_domainadmin }}"
    password: "{{ addc_domainadminpw }}"

- name: Install AD
  win_dsc:
    resource_name: xADDomain
    #ParentDomainName: "{{ addc_parentdomainname }}"
    DomainName: "{{ addc_domainname }}"
    DomainNetBIOSName: "{{ addc_domainnbtname }}"
    # Note: These are NOT used during domain creation. 
    # During an Active Directory deployment the local administrator credentials 
    # are used for the domain administrator.
    DomainAdministratorCredential_username: "{{ addc_domainadmin }}"
    DomainAdministratorCredential_password: "{{ addc_domainadminpw }}"
    SafemodeAdministratorPassword_username: "{{ addc_safemodeadmin }}"
    SafemodeAdministratorPassword_password: "{{ addc_safemodeadminpw }}"
    #DnsDelegationCredential: "{{ dnsdelegation_cred }}"
    DatabasePath: "{{ addc_databasepath }}"
    LogPath: "{{ addc_databaselogpath }}"
    SysVolPath: "{{ addc_sysvolpath }}"
    #ForestMode:
    #DomainMode:
    # TODO need to fix win_psmodule first to make sure it pulls the correct version
    #module_version: "{{ dsc_xactivedirectoryver }}"
  register: InstallAD
# hide PS credentials
  no_log: yes    

- name: Reboot after AD install
  win_reboot:
  when: InstallAD.changed

- name: Create first AD site
  win_dsc:
    resource_name: xADReplicationSite
    name: "{{ addc_firstsite }}"
    RenameDefaultFirstSiteName: true
    # TODO need to fix win_psmodule first to make sure it pulls the correct version
    #module_version: "{{ dsc_xactivedirectoryver }}"

- name: Set DNS forwarders
  win_dsc:
    resource_name: xDnsServerForwarder
    IsSingleInstance: 'Yes'
    IPAddresses:
      - '1.1.1.1'
      - '8.8.8.8'

- name: Set reverse DNS entries
  win_dsc:
    resource_name: xDnsServerADZone
    Name: {{ item }}
    DynamicUpdate: 'Secure'
    ReplicationScope: 'Forest'
  loop: "{{ addc_reverse_dns_zones }}"